# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc8885fc48b4f18af8879fac9270b0b6df868ef4c858709350fb963afd00f7342ea0c5d442ec2b9ef4d6a07aa4f4e24a48e61616108848d801575190abf2aac3

test:
  secret_key_base: 9cb1fe399d25fb6fe2ec3f4757551a2dbb047315255ac7c0d3c43a897acb4b0d4d7348b4c98717b1904f141d1270bcaca4d4861cbd971a05963421b02270fd17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
